<?xml version="1.0"?>

<!-- TODO: double check parameters. If correct, then shape meshes to look better -->
<!-- TODO: add meshes for sensors -->
<!-- TODO: add box blade -->
<robot name="kubo" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find tractor_sim_description)/urdf/kubo.gazebo"/>
  <xacro:include filename="$(find tractor_sim_description)/urdf/kubo_macros.urdf.xacro"/>
  <xacro:include filename="$(find tractor_sim_description)/urdf/lidarx.urdf.xacro"/>

  <!-- Degree-to-radian conversions -->
  <xacro:property name="degrees_45" value="0.785398163"/>
  <xacro:property name="degrees_90" value="1.57079633"/>

  <!-- For documentation for visual of what these parameters are, see repo -->
  <!-- chassis_length is measured along the x axis, chassis_width
       along the y axis, and chassis_height along the z axis.
       Note: Size of chassis won't affect wheel position or function, so be
       careful about making it too big-->

  <!--Length of chassis (m) -->
  <xacro:property name="chassis_length" value="1.1"/>
  <!--Width of chassis (m) -->
  <xacro:property name="chassis_width" value="0.3"/>
  <!--Height of chassis (m) -->
  <xacro:property name="chassis_height" value="0.1"/>
  <!--Mass of chassis (kg) -->
  <xacro:property name="chassis_mass" value="2.788"/>
  <!-- Z Distance from ground (m) -->
  <xacro:property name="chassis_offset" value=".25"/>
  <!-- Distance from center of front tire to center of back tire measured parallel to floor (m) -->
  <xacro:property name="wheelbase" value="1.2"/>

  <!-- Front tire diameter (m) -->
  <xacro:property name="ftire_dia" value="0.5"/>
  <!-- Front tire width (m) -->
  <xacro:property name="ftire_width" value="0.15"/>
  <!-- Front tire mass (kg) -->
  <xacro:property name="fwheel_mass" value="0.29"/>
  <!-- Distance between front wheels (inner side of wheel)-->
  <xacro:property name="fwheel_dist" value="0.8"/>

  <!-- Back tire diameter (m) -->
  <xacro:property name="btire_dia" value="0.7"/>
  <!-- Back tire width (m) -->
  <xacro:property name="btire_width" value="0.2"/>
  <!-- Back tire mass (kg) -->
  <xacro:property name="bwheel_mass" value="0.29"/>
  <!-- Distance between back wheels (inner side of wheel)-->
  <xacro:property name="bwheel_dist" value="0.8"/>

  <!-- Other parameters - currently not used to improve simulation -->
  <!-- Inner diameter of tire, used for inertia measurements. 0 indicates a solid cylinder -->
  <xacro:property name="hub_dia" value="0.0"/>
  <!-- For vehicles with suspension, this is how much the wheels can move up and down -->
  <xacro:property name="wheel_travel" value="0"/>
  <!-- For vehicles with suspension, this sets where the suspension is mounted -->
  <xacro:property name="shock_z_offset" value="0.0655"/>

  <!-- shock_eff_limit is 2 * ((shock_stroke / 2) * shock_spring_constant) N.
       shock_stroke is 0.028575 meters. shock_spring_constant is the shock
       absorber spring's constant in units of N/m. Currently set to arbitrary
       high values to disable shocks behavior  -->
  <xacro:property name="shock_eff_limit" value="1000000"/>
  <xacro:property name="shock_vel_limit" value="1000000"/>

  <!-- Sample calculations for stall torque of a Mabuchi Motor(R) RS-550VC-7525 motor
       num_spur_gear_teeth = 68
       num_pinion_gear_teeth = 19
       final_gear_ratio = (num_spur_gear_teeth / num_pinion_gear_teeth) *
         5.22 = 18.68
       stall_torque = 0.549 N m
       axle_eff_limit = ((2 * stall_torque) * final_gear_ratio) / 4 =
         5.12766 N m
       max_speed = 40 mph (30+ mph) = 17.8816 m/s
       axle_vel_limit = (2 * pi) * (max_speed / (pi * tire_dia)) =
         244.8696 rad/s -->
  <xacro:property name="axle_eff_limit" value="512766"/>
  <xacro:property name="axle_vel_limit" value="2448696"/>

  <!-- motor_stall_torque is measured in N m. motor_no_load_speed is
       measured in rad/s. -->
  <xacro:property name="motor_stall_torque" value="5649"/>
  <xacro:property name="motor_no_load_speed" value="4553"/>

  <xacro:property name="sensorSize" value="0.05"/> <!--TODO: Get rid of this -->
  <xacro:property name="sensorMass" value="0.1"/>


  <!-- base_link must have geometry so that its axes can be displayed in
       rviz. -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </visual>
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- Chassis -->
  <link name="chassis">
    <visual>
      <origin xyz="${chassis_length/2} 0 0" rpy="0 0 ${2*degrees_90}" scale="1 1 1"/>
      <geometry>
        <mesh filename="package://tractor_sim_description/meshes/kubo_chassis.dae"/>
      </geometry>
    </visual>
    <!--
    <visual>
      <origin xyz="${chassis_length / 2} 0 ${chassis_offset}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="chassis_mat"/>
    </visual>
  -->
    <collision>
      <origin xyz="${chassis_length / 2} 0 ${chassis_offset}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>

    <xacro:solid_cuboid_inertial
        width="${chassis_length}" depth="${chassis_width}"
        height="${chassis_height}" mass="${chassis_mass}">
      <origin xyz="0 0 ${-chassis_height / 2}"/>
    </xacro:solid_cuboid_inertial>
  </link>



  <joint name="base_link_to_chassis" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
  </joint>


  <!-- Wheels -->
  <xacro:front_wheel lr_prefix="left" fr_prefix="front"
                     lr_reflect="1" fr_reflect="1"/>
  <xacro:front_wheel lr_prefix="right" fr_prefix="front"
                     lr_reflect="-1" fr_reflect="1"/>
  <xacro:rear_wheel lr_prefix="left" fr_prefix="rear"
                    lr_reflect="1" fr_reflect="-1"/>
  <xacro:rear_wheel lr_prefix="right" fr_prefix="rear"
                    lr_reflect="-1" fr_reflect="-1"/>

  <!-- Sensors -->
  <!-- Sensor positions are relative to base_link
  IMU approximate
https://github.com/olinrobotics/gravl/wiki/Kubo:-Transforms-->
  <!-- Make sure names match gravl localization.launch -->
  <!-- <xacro:gravl_sensor sensor_name="camera"
                x_pos="2.08" y_pos="0" z_pos="1.04"
                x_rot="0" y_rot="0" z_rot="0"/> -->
  <xacro:gravl_sensor sensor_name="imu"
                x_pos="-0.3" y_pos="0" z_pos="1"
                x_rot="0" y_rot="0" z_rot="0"/>
  <!-- <xacro:gravl_sensor sensor_name="hemisphere_gps"
                x_pos="1.94" y_pos="0" z_pos="1.49"
                x_rot="0" y_rot="0" z_rot="0"/>
  <xacro:gravl_sensor sensor_name="gps"
                x_pos="0.3" y_pos="0" z_pos="2.21"
                x_rot="0" y_rot="0" z_rot="0"/>

  <xacro:lidarx parent="base_link" name="lidarx" topic="/lidarx_points" hz="10" samples="440">
    <origin xyz="2.5 0 1.25" rpy="0 0.5 0" />
  </xacro:lidarx> -->

  <!-- Hokuyo Laser -->
  <!-- Using mesh example
  <link name="hokuyo">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://tractor_sim_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz=".15 0 .6" rpy="0 -.1 0"/>
    <parent link="chassis"/>
    <child link="hokuyo"/>
  </joint>
-->


</robot>
